Repository internxt/drive-desktop-linux, pull requests merged in 2025-01, with the labels that each got.

#37 [_]: fix/on-deleted-device-backups-bug
  src/apps/main/device/service.ts
  src/apps/main/preload.d.ts
  src/apps/main/preload.js
  src/apps/main/realtime.ts
  src/apps/renderer/context/DeviceContext.tsx
Labels: bug

#40 [_]: feat/remove-obsolete-github-actions
  .github/workflows/build-windows.yml
  .github/workflows/draft-release.yml
  .github/workflows/e2e-test.yml
  .github/workflows/publish.yml
  .github/workflows/publish_github.yml
Labels: enhancement

#39 Feat/v2.4.1
  .env.example
  .github/workflows/build-windows.yml
  .github/workflows/draft-release.yml
  .github/workflows/e2e-test.yml
  .github/workflows/publish.yml
  .gitignore
  package.json
  release/app/package.json
  src/apps/backups/Backup.ts
  src/apps/backups/batches/AddedFilesBatchCreator.ts
  src/apps/backups/batches/GroupFilesBySize.ts
  src/apps/backups/batches/GroupFilesInChunksBySize.ts
  src/apps/backups/dependency-injection/BackupsDependencyContainerFactory.ts
  src/apps/backups/index.ts
  src/apps/drive/dependency-injection/user/registerUsageServices.ts
  src/apps/drive/fuse/callbacks/FuseCodes.ts
  src/apps/drive/fuse/callbacks/FuseErrors.ts
  src/apps/drive/fuse/callbacks/ReaddirCallback.ts
  src/apps/drive/fuse/callbacks/ReleaseCallback.ts
  src/apps/main/device/service.ts
  src/apps/main/main.ts
  src/apps/main/preload.d.ts
  src/apps/main/preload.js
  src/apps/main/realtime.ts
  src/apps/main/remote-sync/RemoteSyncManager.ts
  src/apps/main/usage/Usage.ts
  src/apps/main/usage/service.ts
  src/apps/main/usage/serviceBuilder.ts
  src/apps/renderer/components/Backups/Delete/ConfirmationModal.tsx
  src/apps/renderer/components/Backups/Delete/DeleteBackups.tsx
  src/apps/renderer/context/DeviceContext.tsx
  src/apps/renderer/pages/Settings/Backups/Selector/BackupFolderSelector.tsx
  src/apps/renderer/pages/Settings/Backups/Selector/BackupsList.tsx
  src/apps/shared/dependency-injection/DependencyInjectionUserProvider.ts
  src/apps/shared/dependency-injection/background/backgroundProcessSharedInfraBuilder.ts
  src/context/local/localFile/application/upload/FileBatchUploader.ts
  src/context/local/localFile/domain/LocalFile.ts
  src/context/local/localFile/domain/LocalFileSize.ts
  src/context/local/localFile/infrastructure/EnvironmentLocalFileUploader.ts
  src/context/storage/TemporalFiles/application/creation/TemporalFileCreator.ts
  src/context/storage/TemporalFiles/application/find/TemporalFileByFolderFinder.ts
  src/context/storage/TemporalFiles/infrastructure/NodeTemporalFileRepository.ts
  src/context/storage/TemporalFiles/infrastructure/downloader/TemporalFileDownloaderFactory.ts
  src/context/storage/TemporalFiles/infrastructure/upload/EnvironmentTemporalFileUploaderFactory.ts
  src/context/storage/thumbnails/infrastructrue/remote/RemoteThumbnailsRepository.ts
  src/context/user/usage/domain/UserUsage.ts
  src/context/user/usage/infrastrucutre/CachedHttpUserUsageRepository.ts
  src/context/user/usage/infrastrucutre/IpcUserUsageRepository.ts
  src/context/virtual-drive/files/infrastructure/SDKRemoteFileSystem.ts
  src/context/virtual-drive/folders/application/FoldersByParentPathLister.ts
  src/context/virtual-drive/folders/infrastructure/HttpRemoteFileSystem.ts
  tests/context/local/localFile/domain/LocalFileSizeMother.ts
  yarn.lock
Labels: bug, enhancement
